global:
  domain: argocd.$MY_PRIVATE_IP.nip.io

configs:
  params:
    server.insecure: true  # disable HTTPS backend

server:
  httproute:
    enabled: true
    parentRefs:
    - name: nginx-shared-gateway
      namespace: nginx-gateway
#   metrics:
#     serviceMonitor:
#       enabled: true
#       namespace: monitoring
#       additionalLabels:
#         release: "prometheus-stack"
# controller:
#   metrics:
#     serviceMonitor:
#       enabled: true
#       namespace: monitoring
#       additionalLabels:
#         release: "prometheus-stack"
# redis:
#   exporter:
#     enabled: true
#   metrics:
#     serviceMonitor:
#       enabled: true
#       namespace: monitoring
#       additionalLabels:
#         release: "prometheus-stack"
# repoServer:
#   metrics:
#     serviceMonitor:
#       enabled: true
#       namespace: monitoring
#       additionalLabels:
#         release: "prometheus-stack"
# dex:
#   metrics:
#     serviceMonitor:
#       enabled: true
#       namespace: monitoring
#       additionalLabels:
#         release: "prometheus-stack"
# applicationSet:
#   metrics:
#     serviceMonitor:
#       enabled: true
#       namespace: monitoring
#       additionalLabels:
#         release: "prometheus-stack"
# notifications:
#   metrics:
#     serviceMonitor:
#       enabled: true
#       namespace: monitoring
#       additionalLabels:
#         release: "prometheus-stack"
