apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: nginx-shared-gateway
  namespace: nginx-gateway
  annotations:
    cert-manager.io/cluster-issuer: selfsigned
spec:
  gatewayClassName: nginx
  listeners:
  - name: http
    hostname: "*.$MY_PRIVATE_IP.nip.io"
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            shared-gateway-access: "true"
  - name: https
    hostname: "*.$MY_PRIVATE_IP.nip.io"
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      certificateRefs:
        - name: shared-gateway-tls
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            shared-gateway-access: "true"
